version: "3"

services:
  bind9:
    container_name: dns-prod-1
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /home/xcad/dns-prod-1/config:/etc/bind
      - /home/xcad/dns-prod-1/cache:/var/cache/bind
      - /home/xcad/dns-prod-1/records:/var/lib/bind
    restart: unless-stopped