version: '3'

volumes:
  teleport-data:
  teleport-certs:

services:
  teleport:
    image: quay.io/gravitational/teleport:10.0.2
    container_name: teleport
    entrypoint: /bin/sh
    command: -c "/usr/bin/dumb-init teleport start -d -c /etc/teleport/teleport.yml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "443:443"
    volumes:
      - .config:/etc/teleport
      - teleport-data:/var/lib/teleport
      - teleport-certs:/mnt/shared/certs